### ISSUE TITLE
ReactSelector sometimes randomly fails

### ISSUE THREAD

**Issue by remetalosse** [DevExpress/testcafe-react-selectors#10]
Hello testcafé team,

So I've been using testcafe-react-selectors since this morning, and though I find this tool extremely useful, I have been puzzled by something.
I use ` material-ui` to get a [Date Picker](http://www.material-ui.com/#/components/date-picker) component into my webpage, and testing this with Testcafé. 

1. Just to test that I've written my test correctly, I try to select the calendar dialog that appears with the Date Picker. By using the React devtools, I see that there is a component named` Calendar`. So I type in  ``
await t.click(ReactSelector('Calendar'))
``.
2. Now, about half of the time, it works just fine, I can see the mouse correctly clicking in the window and the test proceeds the following instructions. But else, I get `The specified selector does not match any element in the DOM tree.`

3. When running the test several times in a row without changing anything, I can get either one result or the other. So I thought maybe this was because the DOM was a tad too slow to completely load, and sometimes the test attempts to click while the DOM is not ready yet. So I added a `.wait(1000)` before the  `.click(ReactSelector('Calendar'))` but it did not change anything.

Would you have an idea of what is causing this? I'm using `testcafe 0.14.0`, `testcafe-react-selectors 0.0.2`, `react 15.4.2`. 

Thanks

**Comment by AlexanderMoskovkin** [comment]
Hi @remetalosse,

I have some thoughts about this, I'm checking them right now.
Meanwhile could you please try to run the test in more slow mode vith the [`speed`](https://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#--speed-factor) option?
`testcafe chrome test.js --speed 0.5 `

**Comment by remetalosse** [comment]
Hello @AlexanderMoskovkin,

When trying at 50% speed, there was a major improvement. The error occurred only 20% of the time. Does this help you pin the problem down? Thanks for your help.

**Comment by AlexanderMoskovkin** [comment]
I can't reproduce it for now. Is it possible to share your page or sources of your page?

**Comment by remetalosse** [comment]
I'm sorry, I can't share it.  But since you can't reproduce it that means the error might be unrelated to testcafe then. I will try to whip up a simple webpage containing only the Date Picker and try again, and transmit you that if it fails.
