### ISSUE TITLE
Support the All selector (“*”)

### ISSUE THREAD

**Issue by bakushin** [DevExpress/testcafe-react-selectors#104]
Hello, I have a site that's similar to the following:
```
<LogInForm>
  <div>
    <form>
      <Field name="name" component="NameField"/>
      <Field name="password" component="PasswordField"/>
      <div>
        <button type="submit" component="LogInButton"/>
      </div>
    </form>
  </div>
</LogInForm>
```

I'm currently able to use the following to grab "name" field:
```
ReactSelector("LogInForm Field").withProps("component", "NameField")
```

I was wondering if there was a way to select each of the elements using _just_ the "component" field, ignoring the value inside of the `ReactSelector`. Each component property will be a unique identifier, so there won't be any conflicts with other elements.

Ideally, it'd be something as simple as `ReactSelector("*").withProps("component", "NameField").

Sorry if this isn't the correct place to ask this, I can't find a forum anywhere to ask such questions. Thank you for the help!

**Comment by kirovboris** [comment]
Hi @cswakamatsu,

Unfortunately, it's impossible to do now. 
I think we can add `*` selector in future releases.

**Comment by cswakamatsu** [comment]
@kirovboris Great, thank you for the update! Do you have an idea when support for this might make it into the roadmap?
