### ISSUE TITLE
ReactSelector is not identifying dropdown box

### ISSUE THREAD

**Issue by vvedachalam** [DevExpress/testcafe-react-selectors#112]
const INDUSTRYDROPDOWN = ReactSelector('SelectInput').withProps('name', 'industry');
is not working, whereas with Testcafe Selector it is working
const INDUSTRYDROPDOWN = Selector('SelectInput').withAttribute('name', 'industry');

Same tried with css and not worked with ReactSelector but again worked with TestCafe selector
const INDUSTRYDROPDOWN = ReactSelector('select[name="industry"]');

is not working, whereas with Testcafe Selector it is working

const INDUSTRYDROPDOWN = Selector('select[name="industry"]');

**Comment by EsaNuurtamo** [comment]
Hi,

I have exactly the same problem with react selectors. I am using Testcafe selectors for dropdowns.

**Comment by kirovboris** [comment]
Hi @EsaNuurtamo, 

Could you please create a minimal working example to reproduce this issue?

**Comment by vvedachalam** [comment]
@kirovboris ,
Sorry it is the other way... ReactSelector is working with react name but not TestCafe Selector

The below is working:
const INDUSTRYDROPDOWN = ReactSelector('SelectInput').withProps('name', 'industry');

TestCafe selector is not working:
const INDUSTRYDROPDOWN = Selector('SelectInput').withAttribute('name', 'industry');

But Selector is working with name locators
const INDUSTRYDROPDOWN = Selector('select[name="industry"]');

I should report it in TestCafe Repo. Can you move it to that project please? 


Page.ts Code:
import { Role, Selector } from 'testcafe'
import { testController } from '../../support/testControllerHolder'
import { waitForReact, ReactSelector } from 'testcafe-react-selectors';

// const INDUSTRYDROPDOWN = ReactSelector('SelectInput').withProps('name', 'industry');
const INDUSTRYDROPDOWN = Selector('SelectInput').withAttribute('name', 'industry');

    getIndustry(){
        return INDUSTRYDROPDOWN.with({ boundTestRun: testController });
    }

=================
pageStep.ts
Given(/^I access mandate form$/, async () => {
    await testController.navigateTo(signuppage.getSignUpURL());
}

Then(/^I can see Industry field$/, async () => {
    await testController
    .expect(signuppage.getIndustry().visible).ok();
}
=============
form.feature
Scenario: Mandate Form is filled successfully
    Given I access mandate form
    Then I can see Industry field

**Comment by kirovboris** [comment]
Yes, the `Selector` constructor doesn't expects a React component name as an argument. Also we don't have any plans to integrate this functionality in testcafe repository yet.

**Comment by vvedachalam** [comment]
@kirovboris started working on new project and I am facing the same issue with ReactSelector. So I want to open this issue

The ReactSelector issue is, when I use eact component name with .withProps, it is working but if I use only react component name, then it is not working.

The below code works
`const INDUSTRYDROPDOWN = ReactSelector('SelectInput').withProps('name', 'industry'); 
`
the below code doesnot work
`const INDUSTRYDROPDOWN = ReactSelector('SelectInput');`

NOTE: TestCafe selector issues is resolved with 0.19.2 version.

**Comment by vvedachalam** [comment]
@kirovboris  Additional info, I am using TestCafe with Cucumber-js with Typescript. 

```
Page.ts Code:
import { Selector } from 'testcafe'
import { testController } from '../../support/testControllerHolder'
import { waitForReact, ReactSelector } from 'testcafe-react-selectors';

const INDUSTRYDROPDOWN = ReactSelector('SelectInput');

getIndustry(){
    return INDUSTRYDROPDOWN.with({ boundTestRun: testController });
}
```
.........
```
pageStep.ts
Given(/^I access mandate form$/, async () => {
await testController.navigateTo(signuppage.getSignUpURL());
}
Then(/^I can see Industry field$/, async () => {
await testController
.expect(signuppage.getIndustry().visible).ok();
}
```
............
```
form.feature
Scenario: Mandate Form is filled successfully
Given I access mandate form
Then I can see Industry field
```

**Comment by Anjaneyulu27** [comment]
hi  guys ,
can u please help me . that we are unable select the values from drop-down menu .
we are having same  path values for all the drop downs in our application.
and we are unable click on upload button also .

**Comment by vvedachalam** [comment]
@Anjaneyulu27 Can you please provide more info? Share the code snippet so that we can see what is the problem
