### ISSUE TITLE
ReactSelector fails to select component when switching frame context

### ISSUE THREAD

**Issue by WebCloud** [DevExpress/testcafe-react-selectors#113]
- `testcafe-react-selectors` version: `2.1.0`
- `testcafe` version: `0.20.4`
- `react` and `react-dom` version:  `16.4.1`

Hello folks. I have noticed an edge case for testcafe `Selector` and `ReactSelector`. We have a react application that lives in an iframe and renders to a separate iframe for fullscreen/takeover dialogs. We were writing test scenarios with testcafe and we noticed that when we upgraded to latest react from 15.x our tests started failing.

The scenarios that it was failing was when rendering and trying to click on an element within the fullscreen iframe. With the `ReactSelector` the selector simply fails to find any element within the newly changed context, using `t.switchToIframe`, timing out and failing the test. We then tried to fallback with `Selector` we can manage to find the element but the click event does not work.

After some small debugging session we found that the `walk` method on the `react16Selector` is able to walk through the react fiber v-dom tree. But for some reason cannot return to the selector the component (I saw that it was there on one of the iterations of `walk`).

With react 15.x it all works fine.

Here's a simplified version of a setup to replicate the problem.

```jsx
const DialogContainer = () => (<button onClick={() => console.log('I have been clicked')}>Click me</button>);
```

```jsx
import * as React from 'react';
import { render } from 'react-dom';

class DialogProvider extends React.Component {
  componentDidUpdate() {
    if (this.props.isVisible) {
      this.props.fullscreenIframe.showIframe();
    } else {
      this.props.fullscreenIframe.hideIframe();
    }
  }

  render() {
    const {

    // dumbed down version of the rendering into a separate frame, which also works as intended
    const renderRoot = this.props.fullscreenIframe.renderRoot;
    render(
        <DialogContainer />,
        renderRoot
      );

    return null;
  }
}
```

```jsx
// main container for the application rendered on the main iframe

const ApplicationContainer = ({
  fullscreenIframe
}) => (
      <View>
      <h1>Hi</h1>
      <DialogProvider isVisible={true} key="app-container-dialog-provider" fullscreenIframe={fullscreenIframe} />
    </View>
);
```

**Comment by kirovboris** [comment]
Hi @WebCloud, 

Thank you for reporting it! I need some time to investigate this issue.

**Comment by kirovboris** [comment]
Sorry for a long response. I built an application with the structure you described but can't reproduce this behavior in simple tests. Could you please provide a simple working sample or a link to your application and test code, so that we can thoroughly research this behavior?

**Comment by WebCloud** [comment]
Sorry for the long time without a response. Been away for a while and did not get time to check back. We can close this, and when I have a better/more reproducible way, I'll get it down on a proper ticket. It might be that our test scenario was bogus and so on.
