### ISSUE TITLE
getReact() fails where getReact(() => {}) succeeds

### ISSUE THREAD

**Issue by ricovitch** [DevExpress/testcafe-react-selectors#114]
## Problem

We have struggled a lot with cases where calling the getReact() API without a callback failed with the following error message : "getReact cannot return DOM elements. Use Selector functions for this purpose"

## Workaround

we found that using the same API with the callback won't throw this error.
There seems to have some inconsistencies in between the two ways of using this API.

## Reproduce

Sorry we did not succeed in getting the getReact errors in an isolated project with simple code. But we suppose it may be a combination of
* use of modals where the dom is out of react root
* use of react context API
* use of react-final-form components (Field)
* use of material-ui input components

## System

* operating system: windows 10 / chrome 67
* testcafe version: 0.20.4 (testcafe-hammerhead@14.1.0, testcafe-react-selectors@2.1.0)
* node.js version: 8.9.2

**Comment by kirovboris** [comment]
Hi @ricovitch,

Unfortunately, `.getReact()` cannot serlialize properties whose values are DOM nodes. 
In your example, the callback filters props values and returns an empty object, which can be serialized.
As a workaround, you can filter DOM nodes like this:

```js
// Suppose we have the following properties:
const props = {
    propName1: 'string',
    propName2: {},
    propName3: document.body
}

// Filtering
const props = await ReactSelector('Component').getReact(({props}) => {
    propName1: props.propName1,
    propName2: props.propName2
});
```
