### ISSUE TITLE
Use reactSelector() for debugging

### ISSUE THREAD

**Issue by Shreky** [DevExpress/testcafe-react-selectors#131]
Hi,
I am using testcafe with testcafe-react-selectors to make e2e tests for my projects.
As testcafe-react-selectors has some limitations (like the nested components search),
I would like to test my selectors in an easy way.

What I am used to is to query the selectors through the console, and play around with document.querySelectorAll() function in order to validate my selector.

I tried to stop with t.debug(), and the test did stopped and let me to open chrome dev tools,
but now I want to understand how I can run the reactSelector() inside the console.

Reading the code, I found that you are creating the reactSelector() available on the window object via: 
$testCafeReactSelector()

This is working properly on the first time, but on the second time it returns an empty array.

For example:
If I just initiated the test and it stopped,
I run:
$testCafeReactSelector("Component")
in the console and it return me an array with the DOM (e.g.: [domElement])
immediately after, I use the same method again and it returns me an empty array (e.g.: []);

**The current behavior:**
> $testCafeReactSelector("Component")
> returns: [domElement]
> $testCafeReactSelector("Component")
> returns: []

**The expected behavior:**
> $testCafeReactSelector("Component")
> returns: [domElement]
> $testCafeReactSelector("Component")
> returns: [domElement]

am I missing something?

Thank you for this useful tool.
Netanel.

**Comment by Shreky** [comment]
@kirovboris ?

**Comment by kirovboris** [comment]
Unfortunately, this method was not intended for debugging purposes. We're going to improve debugging capabilities in the future TestCafe releases.
