### ISSUE TITLE
a duplicate of https://github.com/DevExpress/testcafe-react-selectors/issues/109 (waitForReact exception)

### ISSUE THREAD

**Issue by pgoos** [DevExpress/testcafe-react-selectors#132]
Hi, this is just a duplicate of https://github.com/DevExpress/testcafe-react-selectors/issues/109 - new comments were added proving the issue not to be fixed after it has been previously closed.

Please have a look at the last two comments.

**Comment by chrisshiplet** [comment]
If it helps, I'm reproducing this when using the globally-installed `testcafe` module from the CLI both locally and in the official testcafe docker image. 

If I install the NPM package directly in my project folder and then run the CLI app, it works fine. 

I can also navigate a directory up from the locally installed testcafe and run it via `./project_folder/node_modules/testcafe/bin/testcafe-with-v8-flag-filter.js chrome test.js` and it works fine, so it doesn't seem to be a working directory issue. 

Unfortunately, the docker image seems to default to using a globally installed testcafe, so I haven't managed to make it work at all there.

**Comment by kirovboris** [comment]
This issue relates to the TestCafe repository:
DevExpress/testcafe#3186
Track this issue to be aware about progress.
