### ISSUE TITLE
IE11 NoModificationAllowedError, out of stack space

### ISSUE THREAD

**Issue by mwq27** [DevExpress/testcafe-react-selectors#139]
I'm trying run tests using a remote browser connection in IE11. Before the test page even loads, the console is flooded with logs of `SCRIPT28: Out of stack space`, and then `SCRIPT5022: NoModificationAllowedError -> hammerhead.js (8,. 20470)`. My tests run perfectly fine in Chrome and Firefox.

Sometimes the login page actually loads as the test is about to begin, but the browser locks up. I am able to verify that the `before` and `beforeEach` hooks are working.
![screenshot 2019-02-12 22 07 31](https://user-images.githubusercontent.com/551359/52686692-79c02e00-2f14-11e9-9828-c84ddd3d61bc.png)

### Testcafe Version:
0.23.1

### Machine:
Mac OS Mojave

**Comment by LavrovArtem** [comment]
We've already faced same errors and fixed it in higher releases. Let's try to update your testcafe version to `1.0.0`.

**Comment by mwq27** [comment]
Oh wow I didn't know that 1.0.0 was released.  Thanks @LavrovArtem :)

**Comment by mwq27** [comment]
Closing, upgrading to 1.0.0 was the solution.
