### ISSUE TITLE
witeForReace() fails when run test in multiple browsers

### ISSUE THREAD

**Issue by maximkoev** [DevExpress/testcafe-react-selectors#143]
Steps

* run tests on all locally installed browsers (testcafe all)
Expected: all tests run correctly
Actual result: all tests fail due to waiting time out exceed
note: if I specify list of browsers manually have the same result

 1) - Error in fixture.beforeEach hook -
      An error occurred in ClientFunction code:

      waitForReact: The waiting timeout is exceeded

  Browser: IE 11.0.0 / Windows 10.0.0
      Screenshot: C:\Users\MaximKoev\cap-mvp\packages\automation\reports\screenshots\2019-06-13_18-33-14\check that all elements are present in footer on home page\Training terms is
      present in footer\IE_11.0.0_Windows_10.0.0.png

         1622 |                stopChecking = true;
         1623 |
         1624 |                reject('waitForReact: The waiting timeout is exceeded');
         1625 |            }, checkTimeout);
         1626 |        });
       > 1627 |    }, { dependencies: { checkTimeout } })();
         1628 |};

p.s. I use windows 10

![image](https://user-images.githubusercontent.com/15101695/59447548-15eb3a80-8e0c-11e9-85f9-a798ec72b12c.png)

**Comment by AndreyBelym** [comment]
Looks like this error only happens in IE11. Have you tried to run your test in IE only? Have you checked that your web app works in IE11?
