### ISSUE TITLE
waitForReact fails when called from node callback

### ISSUE THREAD

**Issue by theoinglis** [DevExpress/testcafe-react-selectors#148]
I have created a PR for this issue:
https://github.com/DevExpress/testcafe-react-selectors/pull/147

it is simply to allow the testController to be passed in when the testController can't be picked up automatically and is for this edge case:
https://devexpress.github.io/testcafe/documentation/test-api/selecting-page-elements/selectors/edge-cases-and-limitations.html#calling-selectors-from-nodejs-callbacks

There are further details in the PR. 

Please let me know if you need any more information.

Thanks!

**Comment by AlexKamaev** [comment]
Thank you for contributing to TestCafe. We will review your PR and give you feedback. I'll close this issue since I think it's better to continue the discussion about your PR in its [own thread](https://github.com/DevExpress/testcafe-react-selectors/pull/147).

**Comment by kirovboris** [comment]
I've published `testcafe-react-selectors@3.2.0`

**Comment by theoinglis** [comment]
Thanks very much!
