### ISSUE TITLE
Cannot find testcafe-react-selectors module error 

### ISSUE THREAD

**Issue by ipalkar** [DevExpress/testcafe-react-selectors#151]
<img width="957" alt="Screen Shot 2019-09-11 at 11 00 44 AM" src="https://user-images.githubusercontent.com/48535292/64722500-7168ab00-d483-11e9-9502-272dde1e5745.png">
I am getting this error even though I have installed the testcafe react selectors module

**Comment by ipalkar** [comment]
fixed

**Comment by 2BC-Wasabi** [comment]
i have the same problem more or less, i get 
` Cannot find module 'testcafe-react-selectors' or its corresponding type declarations.`
would be nice if you could have shared your fix
