### ISSUE TITLE
React selector not finding component if it is inside nested root container 

### ISSUE THREAD

**Issue by franklinjose** [DevExpress/testcafe-react-selectors#159]
This is not an issue if it is react 15 , since it is relying on `data-reactroot` attribute on the element and `const rootEls = [].slice.call(document.querySelectorAll('[data-reactroot]'));` this code will find all nested root containers. 

In react 16 the way to identify root container is using object key  `el._reactRootContainer` and `getRootElsReact16(el)`  only looking for peers not nested containers. 
For e.g. it will work in below structure
`<body>`
 `<div/> `// First root container
`<div/>` // Second root container (peer of first)
......
`</body>`

Will not work in below structure (In this case it will find components that is part of first root container , not from second and Third root container)
`<body>`
    `    <div>` // First root container
       `    <div>` // Second root container (Nested inside First) `</div>`
       `    <div> `// Not a react container `</div>`
      `    <div>` // Third root container (Nested inside First) ` </div>`
   `   </div>`
`</body>`

**Comment by Farfurix** [comment]
@franklinjose

Hello,

Can you please create a simple project that we can run on our side to reproduce the "nested root container" issue?

**Comment by franklinjose** [comment]
Here is the [sample project](https://github.com/franklinjose/nested-react-root) with repro.
Thank you for the quick response!

**Comment by AndreyBelym** [comment]
Thank you for the example, I've reproduced the issue.

**Comment by franklinjose** [comment]
Please review this PR for this issue

**Comment by AndreyBelym** [comment]
Thank you for your contribution. It's fine by me, but let's wait until a better skilled React developer reviews your PR 😊

**Comment by franklinjose** [comment]
Thank you for taking time to review !

**Comment by kirovboris** [comment]
Closed by https://github.com/DevExpress/testcafe-react-selectors/pull/160

**Comment by kirovboris** [comment]
Published `testcafe-react-selectors@4.0.0`

**Comment by franklinjose** [comment]
Thank you that was quick!!
