### ISSUE TITLE
Support React 17

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-react-selectors#171]
I'm working on it.

**Comment by oguera** [comment]
Do you need any assistance here?

**Comment by arubtsov** [comment]
@oguera, Thank you for your willingness to help. At this point, we need to understand to what extend things have changed in React 17. Our team is working on this issue. We will leave a comment here if any help is needed in implementation or testing.

**Comment by oguera** [comment]
It looks like you are right on track here. I'll just link the PR where you are working on the React17 support in this issue for transparency:

https://github.com/DevExpress/testcafe-react-selectors/pull/173

**Comment by kirovboris** [comment]
Published `testcafe-react-selectors@4.1.0`
