### ISSUE TITLE
Can't get it work with latest NextJS

### ISSUE THREAD

**Issue by FDiskas** [DevExpress/testcafe-react-selectors#203]
I was not able to fix the issue.
Thank you for any help or suggestions

https://github.com/FDiskas/devtalks-e2e/tree/testcafe

![image](https://github.com/DevExpress/testcafe-react-selectors/assets/468006/5e00d7bc-a1e2-44cf-b019-cfcab146301b)

**Comment by PavelMor25** [comment]
Hello @FDiskas,

We appreciate you taking the time to share the information about this issue. We replicated it, and it is currently in our internal queue. Please note that the research may take time. We'll update this thread once we have news.
