### ISSUE TITLE
Should support typescript definition

### ISSUE THREAD

**Issue by mario8x** [DevExpress/testcafe-react-selectors#25]
I think that we should support typescript definition for this module. 
Because we use typescript to develop test script.

**Comment by kirovboris** [comment]
Hi @mario8x,
We're going to support TypeScript syntax in all selector plugins soon.

**Comment by dmcclurealinta** [comment]
What's the status of the enhancement?

**Comment by kirovboris** [comment]
Hi @dmcclurealinta,
You already can write tests with typescript, we just need to add little more docs for it.

**Comment by dmcclurealinta** [comment]
Hi @kirovboris,
Ah, yes I have been utilizing it with `import * as ReactSelector from 'testcafe-react-selectors';`
Just would be nice to have the auto complete functionality like you get with regular testcafe selectors using Selector.

**Comment by vitalics** [comment]
Hi all, I was create PR for add more strongly types for existing code. Also, create a new type for pretty describing expected components. Example:
``` ts
import {} from 'testcafe-react-selectors'
type MyButtonProps = {someProp:number};
type myButtonComponent = ReactComponent<MyButtonProps>;
test('my test for button', async t =>{
  const button = ReactSelector('MyButton');
  const buttonAsComponent = button.getReact<myButtonComponent>();
  // or
  // P.S. automplete helps you
  await t.expect(button.getReact<myButtonComponent>( ({ props }) => props.someProp)).typeof('number');

})
```

**Comment by kirovboris** [comment]
Hi, thank you for your contribution! I'll check this out soon.

**Comment by vitalics** [comment]
I suppose that we can close this issue
