### ISSUE TITLE
Unable to install testcafe-react-selectors

### ISSUE THREAD

**Issue by Sanjay9889** [DevExpress/testcafe-react-selectors#27]
C:\Users\abc>npm install -g testcafe
C:\Users\abc\AppData\Roaming\npm\testcafe -> C:\Users\skumar21\AppData\Roam
ing\npm\node_modules\testcafe\bin\testcafe-with-v8-flag-filter.js
+ testcafe@0.16.1
updated 6 packages in 31.174s

C:\Users\abc>npm install -g testcafe-react-selectors
npm WARN testcafe-react-selectors@0.0.5 requires a peer of testcafe@* but none w
as installed.

+ testcafe-react-selectors@0.0.5
updated 1 package in 0.656s

**Comment by kirovboris** [comment]
Hi @Sanjay9889,

This warning message is global `peerDependencies` specifics in npm and it doesn't influence the plugin operating.
As a workaround, you can use 
```
npm install -g testcafe testcafe-react-selectors
```
to avoid the warning message.
