### ISSUE TITLE
selecting an attribute

### ISSUE THREAD

**Issue by neelay** [DevExpress/testcafe-react-selectors#29]
In this example from the home page of testcafe-react-selectors. 
If I want to store the attribute value "Low"  in a variable. 
How would i do that.  I am newbie in javascript, just in case if i am doing something totally noob wrong here. 

I have been trying the following, and it does not work for me. 
```javascript
<TodoApp className="todo-app">
    <TodoInput />
    <TodoList>
        <TodoItem priority="High">Item 1</TodoItem>
        <TodoItem priority="Low">Item 2</TodoItem>
    </TodoList>   
    
    <div className="items-count">Items count: <span>{this.state.itemCount}</span></div>
</TodoApp>

const el = ReactSelector('TodoList');
const low_value =el.getReact(({ props }) => props.priority==='Low'

```

**Comment by kirovboris** [comment]
The `TodoList` component doesn't have the `priority` property. You should get a selector for the `TodoItem` component.
You can store your property value to a variable in the following way:
```js
const el = ReactSelector('TodoItem');
 
const low_value = await el.getReact(({ props }) => props.priority);
```
The `({ props }) => props.priority` handler returns the component's `priority` property value for the `el` selector.
You can write it this way as well
```js
const el = ReactSelector('TodoItem');
 
const low_value = el.getReact(({ props }) => props.priority);
```
In this case `low_value` will contain `ClientFunction`, which will be automatically executed in an assertion:
```js
const low_value = el.getReact(({ props }) => props.priority);
 
await t.expect(low_value).eql('Low');
 
//OR
 
await t.expect(el.getReact(({ props }) => props.priority)).eql('Low');
 
```

**Comment by neelay** [comment]
<img width="994" alt="screen shot 2017-07-31 at 1 22 14 pm" src="https://user-images.githubusercontent.com/1371841/28767937-5f39da44-75f3-11e7-9175-142f2dea100f.png">
Thank you @kirovboris for responding. 

Sorry for delayed response from my end. I have tried the option as you suggested on my  end, but i am not able to get the value. 

```
this.button = ReactSelector('ButtonBar button')
this.button2 = ReactSelector('button')

const abc =  this.button.getReact(({ props }) => props.name==='SignIn');
const abc2 =  this.button2.getReact(({ props }) => props.name==='SignIn);

console.log(abc)
console.log(abc2)
```

Both of the above return 

`ClientFunctionResultPromise { _then: [], _fn: [Function], _taskPromise: null }`


I get a Promise as a return. I am looking for values SignIn and Register. So that I can click on them and proceed.

**Comment by kirovboris** [comment]
It's the correct behavior that `abc` and `abc2` return `ClientFunctionResultPromise`. 
`.getReact()` is [`ClientFunciton`](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#creating-client-functions) in context of TestCafe.
Assertions can automatically resolve promises returned by `ClientFunction`.
If you want to output a result value in the console, you should use 
```js
console.log(await abc);
console.log(await abc2);
```
This description is missing in our documentation of `testcafe-react-selectors`. We plan to fix it soon.
