### ISSUE TITLE
Cannot assert based on props or state

### ISSUE THREAD

**Issue by dimaip** [DevExpress/testcafe-react-selectors#32]
Hey, I log in to a page that has a React component LeftSideBar and try to assert on its props:
```
    const leftSideBar = ReactSelector('LeftSideBar');
    await t
        .typeText('#username', 'user')
        .typeText('#password', '*******')
        .click('button.login');
    await t.wait(8000);
    await t.expect(leftSideBar.getReact().props.isHidden).eql(false);
```
But get `1) TypeError: Cannot read property 'isHidden' of undefined`

The same is happening with the state, seems to be undefined too.
Any tips why that may be happening?

**Comment by dimaip** [comment]
Pretty strange, once rewritten to `await t.expect(leftSideBar.getReact(({props}) => props.isHidden)).eql(true);` it works!

**Comment by kirovboris** [comment]
Hi @dimaip,

The `getReact()` method returns `Promise`, so the `props` field is `undefined`. 
It can be rewritten properly the following way
```js
await t.expect((await leftSideBar.getReact()).props.isHidden).eql(false);
```
On the other hand, the expression
```js
leftSideBar.getReact(({props}) => props.isHidden)
```
also returns `Promise`, which is a result of execution [`ClientFunction`](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#creating-client-functions).
Such promises can be resolved automatically by [assertion functions](https://devexpress.github.io/testcafe/documentation/test-api/assertions/), so 
```js
await t.expect(leftSideBar.getReact(({props}) => props.isHidden)).eql(true);
```
is an equivalent of
```js
await t.expect(await leftSideBar.getReact(({props}) => props.isHidden)).eql(true);
```

**Comment by dimaip** [comment]
Hi @kirovboris! I appreciate your quick feedback!
But in the docs there's this example which doesn't seem to have await:
```
await t.expect(el.getReact().props.priority).eql('High');
```
Why does it work, and my original assertion didn't?

**Comment by kirovboris** [comment]
Thank you for feedback! My bad, it mustn't work. I'll fix the documentation soon.

**Comment by dimaip** [comment]
Awesome! Feel free to close the issue as soon as you have updated it. Can imagine some other people might get tipped over it too :)
