### ISSUE TITLE
Doesn't work with Nightmare

### ISSUE THREAD

**Issue by dimaip** [DevExpress/testcafe-react-selectors#35]
I get this error when trying to use react selectors with nightmarejs provider:
```
An error occurred in Selector code:
Error: testcafe-react-selectors supports React version 15.x and newer
Browser: Electron 1.7.5 / Linux 0.0.0
```
When trying as simple as:
```
await t.expect(ReactSelector('Xyz').exists).ok();
```
The same code works with chrome.

**Comment by AndreyBelym** [comment]
Hello @dimaip! Unfortunately, we can't reproduce this problem, our tests are working fine in Nightmare. Can you share a link to the page or maybe code of the page on which you have encountered the problem?

**Comment by dimaip** [comment]
Hi @AndreyBelym!
I'll try to make a portable example and reopen the issue if I succeed to do so. Unfortunately, the whole app is too big and interacts with the server, to just share it.

**Comment by dimaip** [comment]
It seems this problem is not related to react selectors, my app just doesn't login with nightmare.
