### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by kirovboris** [DevExpress/testcafe-react-selectors#55]
React 16 has other `ReactDOM` implementation, so we should investigate and support it.

**Comment by WonSong** [comment]
Any progress on this?

**Comment by kirovboris** [comment]
Hi @WonSong,

We're going to support it soon, but we still need some time to investigate the new `ReactDOM` implementation.

**Comment by kirovboris** [comment]
I've just publish `testcafe-react-selectors@1.0.0` with React 16 support.

**Comment by tgigsigniant** [comment]
Hi @kirovboris I am having an issue with React 16 and testcafe-react-selectors v1 that results in the following error:

Managing members
 ✖ Find logged in user in member list and verify you can't delete yourself

   1) Error on page "http://localhost:3000":

      Uncaught TypeError: Cannot read property 'call' of undefined

      Browser: Chrome 61.0.3163 / Mac OS X 10.12.6

          9 |    return await submitButton.with({visibilityCheck:
      true})();
         10 |}
         11 |
         12 |export function enterUsernameAndPassword (t, username,
      password) {
         13 |    return t
       > 14 |        .typeText(emailInput, username)
         15 |        .typeText(passwordInput, password);
         16 |}
         17 |
         18 |export function submitLoginForm (t) {
         19 |    return t.click(submitButton);

         at enterUsernameAndPassword

**Here are the code snippets**

```
export const getMembers = () => ReactSelector('Member');

export const getMember = (emailAddress) => getMembers().withText(emailAddress);

test('Find logged in user in member list and verify you can\'t delete yourself', async (t) => {
    await doLogin(t, username, password);
    await clickSideMenuItem(t, 'Members');
    const memberSelector = getMember(username);
    await t.expect(memberSelector.count).eql(1);  //Fails here
    await deleteMember(t, username);
    await closeCantDeleteYourselfDialog(t);
    await t.expect(memberSelector.count).eql(1);
});
```

Thanks

**Comment by kirovboris** [comment]
Hi @tgigsigniant,

Could you please provide us a link to your web application or a small reproducible example?
Please try to add a timeout before `getMember(username)`. It's possible that the reactjs application was not yet loaded if the page url changed after the previous action.
Please let me know if this helps. It seems that building ReactDOM v16 at application startup takes a bit more time. 

```js
test('Find logged in user in member list and verify you can\'t delete yourself', async (t) => {
    await doLogin(t, username, password);
    await clickSideMenuItem(t, 'Members');

    await t.wait(1000);

    const memberSelector = getMember(username);
    await t.expect(memberSelector.count).eql(1);  //Fails here
    await deleteMember(t, username);
    await closeCantDeleteYourselfDialog(t);
    await t.expect(memberSelector.count).eql(1);
});
```

**Comment by tgigsigniant** [comment]
Thank you for your quick response @kirovboris,

I tried adding a wait statement like you mentioned above and it did not work unfortunately (the dom seems to be getting rendered correctly). 

Just an FYI we have just migrated our project to React 16. This automation test was passing successfully with React v15, "testcafe": "^0.16.2", and "testcafe-react-selectors": "^0.0.5".

I made a small reproducible example using the create-react-app and I added a Member component similar to what I have in the actual app, and the test is failing :

https://github.com/tgigsigniant/react-testcafe-sample-app

`yarn
yarn start
node ./node_modules/testcafe/bin/testcafe.js chrome ./automation
`

**Comment by tgigsigniant** [comment]
Thank you for your quick response @kirovboris,

I performed both of your recommendations, I added the `await t.wait(1000);` statement without success unfortunately. 

I also created a smaller example project using create-react-app (https://github.com/tgigsigniant/react-testcafe-sample-app) that mimicked the Member component from the main project that I wanted to verify. The sample project's automation test is working correctly without errors. 

However, the main project still fails for some reason (an FYI we have just migrated our project to React 16. This automation test was passing successfully with React v15, "testcafe": "^0.16.2", and "testcafe-react-selectors": "^0.0.5")

I was switching branches yesterday in the main project so I beilive did not have the correct version of testcafe-react-selectors (v0.0.5 instead of v1.0.0) when the error message I provided you was printed. Below is the actual message from v1.0.0, if this message gives you any other leads let me know.

Managing members
 ✖ Find logged in user in member list and verify you can't delete yourself

   1) An error occurred in Selector code:

      TypeError: Cannot read property 'container' of null  **//Different error message mentioned above**

      Browser: Chrome 61.0.3163 / Mac OS X 10.12.6

         11 |    await doLogin(t, username, password);
         12 |    await clickSideMenuItem(t, 'Members');
         13 |    await t.wait(1000);
         14 |    const memberSelector = getMember(username);
         15 |
       16 |    await t.expect(memberSelector.count).eql(1); **This is where the error is occuring**


Otherwise, we may do more internal debugging by running both projects side-by-side to see if we find any differences.

**Comment by kirovboris** [comment]
Many thanks, @tgigsigniant. I've reproduced this issue. I'll fix it as soon as possible.

**Comment by kirovboris** [comment]
I've just published `testcafe-react-selectors@1.0.1`. Could you check it please?

**Comment by tgigsigniant** [comment]
Awesome thanks @kirovboris, I just checked it out it works perfectly now!

**Comment by jaxxreal** [comment]
The same error w/ `testcafe-react-selectors@^2.0.1`

**Comment by kirovboris** [comment]
Hi @jaxxreal, 
Detecting of the react version wasn't changed in `testcafe-react-selectors@^2.0.1`. 
Could you please check if the react application is loaded on the test start. You can add a small timeout to make sure the app is loaded, e.g.
```js
fixture`...`
.page`...`
.beforeEach(t => {
    t.wait(2000);
});
```

**Comment by kirovboris** [comment]
We added [`waitForReact`](https://github.com/DevExpress/testcafe-react-selectors#wait-for-application-to-be-ready-to-run-tests) in `testcafe-react-selectors@2.1.0` to wait for the loading of the component tree.
