### ISSUE TITLE
Mac OS X - Unable install testcafe-react-selectors properly

### ISSUE THREAD

**Issue by RustomMurad** [DevExpress/testcafe-react-selectors#68]
1)Tried install with -g flag:
Romans-MacBook-Pro:TestCafe romanlagunov$ npm -g install testcafe-react-selectors
npm WARN testcafe-react-selectors@1.0.2 requires a peer of testcafe@* but none is installed. You must install peer dependencies yourself.

+ testcafe-react-selectors@1.0.2
updated 1 package in 0.571s

Ran:
Romans-MacBook-Pro:TestCafe romanlagunov$ testcafe chrome anaplan-launchpad.js 
ERROR Cannot prepare tests due to an error.

Error: Cannot find module 'testcafe-react-selectors'
    at Object.<anonymous> (/Users/romanlagunov/TestCafe/anaplan-launchpad.js:2:1)

Type "testcafe -h" for help.
 2) Tried install locally (w/0 -g flag):

Romans-MacBook-Pro:TestCafe romanlagunov$ npm install testcafe-react-selectors
npm WARN saveError ENOENT: no such file or directory, open '/Users/romanlagunov/TestCafe/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/romanlagunov/TestCafe/package.json'
npm WARN testcafe-react-selectors@1.0.2 requires a peer of testcafe@* but none is installed. You must install peer dependencies yourself.
npm WARN TestCafe No description
npm WARN TestCafe No repository field.
npm WARN TestCafe No README data
npm WARN TestCafe No license field.

+ testcafe-react-selectors@1.0.2
added 1 package in 0.962s

Ran again:
Romans-MacBook-Pro:TestCafe romanlagunov$ testcafe chrome anaplan-launchpad.js 
ERROR Cannot prepare tests due to an error.

Got different error
Error: Cannot find module 'testcafe'
    at Object.<anonymous> (/Users/romanlagunov/TestCafe/node_modules/testcafe-react-selectors/lib/index.js:7:16)
    at Object.<anonymous> (/Users/romanlagunov/TestCafe/anaplan-launchpad.js:2:1)

Type "testcafe -h" for help.

PS.  Import statment in anaplan-launchpad.js script:
import ReactSelector from 'testcafe-react-selectors';

**Comment by kirovboris** [comment]
Hi @RustomMurad,

`testcafe-react-selectors` requires installed `testcafe` module.
You should install `testcafe` before `testcafe-react-selectors`:
```bash
npm install -g testcafe testcafe-react-selectors
```
or for local installation
```bash
npm install testcafe testcafe-react-selectors
```
