### ISSUE TITLE
getReact doesn't return correct props

### ISSUE THREAD

**Issue by edmundas-ramanauskas** [DevExpress/testcafe-react-selectors#77]
We still have a case where I can't solve failing test properly. In most cases where I observed failing tests it's usually in place where we use higher order components. so in some cases the problem is solved if I change nesting level (because some props are past to multiple components down the line). in other cases, it helps only if I remove higher order component or replace it with some other, but this is not a solution for us.
for example currently I have situation where I have a connected container and some dumb components beneath it. and if I remove connection to redux store and replace it with something else - tests are passing. and I tried to reproduce this issue in my demo app (3rd test):
https://github.com/edmundas-ramanauskas/testcafe-demo/blob/master/tests/example.spec.js
but it doesn't work exactly the same way, but maybe it will give you a hint what could be wrong.
because in my case it fails for all options, and it's fixed if I remove connection to redux store. and in this demo app it fails only for second option, and it doesn't matter if it's connected to redux store. also if I change nesting level (check Toggle instead of Option component) - it works.
it's a long write, but I hope it will make sense for you :)

**Comment by kirovboris** [comment]
Hi @edmundas-ramanauskas,

Thank you for information. I'll investigate carefully your examples and let you know if some assistance is required.

**Comment by kirovboris** [comment]
I've just published `testcafe-react-selectors@1.0.5`. Could you please check it?

**Comment by edmundas-ramanauskas** [comment]
sure, will do asap

**Comment by edmundas-ramanauskas** [comment]
@kirovboris all our problems are solved now, thanks a lot!

**Comment by kirovboris** [comment]
You're welcome!
