### ISSUE TITLE
How do I select a component based on props?

### ISSUE THREAD

**Issue by jacobwgillespie** [DevExpress/testcafe-react-selectors#81]
Apologies if this is published somewhere, but I cannot seem to determine how to select a component based on its props.

What I want is something that works like the following:

```javascript
const sectionOne = ReactSelector('Section')
  .filter(el => el.getReact(({props: {name}}) => name === 'one'))

const sectionTwo = ReactSelector('Section')
  .filter(el => el.getReact(({props: {name}}) => name === 'two'))
```

Or some other way where I can target specific components based on their props.  Is this possible?  It may be that I'm just not familiar enough with selectors to understand how to accomplish this.  I know that my example breaks because the filter predicate function is executed on the client.  It feels like this should be a very common use-case, so I'm hoping I am just unfamiliar with the solution.

**Comment by kirovboris** [comment]
Hi @jacobwgillespie,

Unfortunately, it's impossible to do it now.
We're working on this functionality  and going to implement the `.withProps(propName, value)` method. You can track this issue to be informed of our progress - https://github.com/DevExpress/testcafe-react-selectors/issues/14
