### ISSUE TITLE
getReact cannot return DOM elements. Use Selector functions for this purpose.

### ISSUE THREAD

**Issue by eliw00d** [DevExpress/testcafe-react-selectors#91]
I am trying to use getReact in the following manner:

```
title = () => ReactSelector('cssSelector')
        .getReact(({props}) => props.title)
```
and then
```
let data = {
    title: await this.title(),
    // other data
}
```
but I see the following error:
```
getReact cannot return DOM elements. Use Selector functions for this purpose.
```
I was expecting to return the prop's value, but I guess that is not the case? I am trying to create a data object containing props, textContent, etc. of various selectors in a page object for later assertion.

I am using:
```
"testcafe": "0.19.1",
"testcafe-react-selectors": "1.0.6"
```

**Comment by kirovboris** [comment]
Hi @eliw00d ,

What does `props.title` return?

Internally, `.getReact()` uses a [ClientFunction](https://devexpress.github.io/testcafe/documentation/test-api/obtaining-data-from-the-client.html#creating-client-functions) that doesn't wait for the DOM node as the result.
If `props.title` returns a DOM node, you can calculate textContent via 
```js
ReactSelector('ComponentName').textContent
//or
ReactSelector('ComponentName tagName').textContent
```
 
or via a regular Selector 
```js
Selector('CSSSelector').textContent
```

**Comment by eliw00d** [comment]
As far as I know it is just a string, with propType of node. I am having a strange issue where one specific usage of this component is returning an empty string for textContent, so I thought using props.title would give me the string instead and work for all cases.

**Comment by eliw00d** [comment]
I even get the error when doing this:
```
const react = await ReactSelector('MyComponent').getReact()
```

**Comment by kirovboris** [comment]
Could you provide please the link to web page or create a minimal working example to reproduce this issue?

**Comment by eliw00d** [comment]
It turns out that we are using https://github.com/marnusw/react-css-transition-replace to animate from a loading state to a loaded state. The loading state has a lot of the same components with no data, so the selector is picking up the loading version of the component instead of the loaded version. How could we handle the transition so that we get the loaded version of the component?

I'll try to come up with a minimal working example.

**Comment by kirovboris** [comment]
I see the only way now - the using of the [smart assertion mechanism](http://devexpress.github.io/testcafe/documentation/test-api/assertions/#smart-assertion-query-mechanism) to wait for the component with new state or props, e.g.:
```js
await t
     .expect(ReactSelector('MyComponent').getReact(({state}) => state.propName))
     //OR
     .expect(ReactSelector('MyComponent').getReact(({props}) => props.propName))

     .eql('someValue', { timeout: 10000 }) 
     .click() //do some actions
```
Also example would be very useful.

**Comment by eliw00d** [comment]
So, we are using the Page Model to create page objects that have selectors and actions to handle navigation in the site. Some of our pages have a loading transition where there are placeholders instead of the loaded child elements. The issue we were having is that the selectors were getting the placeholders instead of the loaded child elements.

I think I figured out a way around this, not sure if it would be possible without the recent addition of withProps. 
```
let myComponent = ReactSelector('MyComponent').withProps({loading: false})
let isLoaded = await myComponent()()
let otherComponent = myComponent.find('div').withAttributes('class', /SomeClass/)
let title = await otherComponent.textContent
```
This seems to work!

Now we just need findReact and we're all set. :)

Thanks for the help!
