### ISSUE TITLE
withProps: allow partial matching of a prop that's an object

### ISSUE THREAD

**Issue by ktj** [DevExpress/testcafe-react-selectors#98]
Example I have
```
<List>
  <ListItem someProp={{ type: 'foobar', label: 'some random text' }} />
...
```
And a selector
```
ReactSelector('List').findReact('ListItem').withProp({ someProp: { type: 'foobar' } });
```

**Comment by kirovboris** [comment]
Hi @ktj,
Thank you for the suggestion. I agree it can be a quite useful feature. I need to figure out API for this feature.

**Comment by NanjoW** [comment]
Any news on this feature. Partial matching of objects in props would be great.

**Comment by rafalskalski** [comment]
Same as above, this would really make a difference. Any suggestions on how to deal with that meanwhile ?

**Comment by kirovboris** [comment]
I'm going to implement it soon. I think the partial matching should be default behaviour, because it more common case. What do yo think?

**Comment by rafalskalski** [comment]
Definietly default, not sure if that’s case for everyone, but I often work with objects that have large number of props so in my case its most common scenario.

**Comment by kirovboris** [comment]
Implemented in `testcafe-react-selectors@3.0.0`

**Comment by saikumarr** [comment]
Can we do the same with array of strings.
withProps to allow partial matching of a prop that' an array.

`<Card tags=['tag1','tag2']/>`

`ReactSelector('Card').withProps('tags', ['tag1'])`
 should give me all the ones that has 'tag1' but the partial matches are not returned

**Comment by Farfurix** [comment]
@saikumarr 

Hello,

Thank you for your suggestion. I created a new issue about it: https://github.com/DevExpress/testcafe-react-selectors/issues/158.

I cannot give you any estimate as to when this functionality will be implemented. Of course, your PR is welcome.
